# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 180817bbe5a2db5e419a37d45d181e40d39be3cbc05783cbbfcbfc4f91f1c7620585ab21b5acb31cf198bafd64b7bbaaccced5247522bada5c150a44ea4ba01b

test:
  secret_key_base: fa7256f7db0e3eb3f8e1bfb7a32f32b838a5984925afbcd9b7d53476f39d15294371c669cb8bbee60c4dadd6a36e73a439d439a7624539862b94ea8954b1a6b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
